// business units
export const CLEAR_BUSINESS_UNIT = "businessUnit@CLEAR_BUSINESS_UNIT"
// fetch business units
export const FETCH_BUSINESS_UNITS_INIT = "businessUnits@FETCH_BUSINESS_UNITS_INIT"
export const FETCH_BUSINESS_UNITS_SUCCEDED = "businessUnits@FETCH_BUSINESS_UNITS_SUCCEDED"
export const FETCH_BUSINESS_UNITS_FAILED = "businessUnits@FETCH_BUSINESS_UNITS_FAILED"
// fetch business unit
export const FETCH_BUSINESS_UNIT_INIT = "businessUnit@FETCH_BUSINESS_UNIT_INIT"
export const FETCH_BUSINESS_UNIT_SUCCEDED = "businessUnit@FETCH_BUSINESS_UNIT_SUCCEDED"
export const FETCH_BUSINESS_UNIT_FAILED = "businessUnit@FETCH_BUSINESS_UNIT_FAILED"
// create business unit
export const CREATE_BUSINESS_UNIT_INIT = "businessUnit@CREATE_BUSINESS_UNIT_INIT"
export const CREATE_BUSINESS_UNIT_SUCCEDED = "businessUnit@CREATE_BUSINESS_UNIT_SUCCEDED"
export const CREATE_BUSINESS_UNIT_FAILED = "businessUnit@CREATE_BUSINESS_UNIT_FAILED"
// edit business unit
export const EDIT_BUSINESS_UNIT_INIT = "businessUnit@EDIT_BUSINESS_UNIT_INIT"
export const EDIT_BUSINESS_UNIT_SUCCEDED = "businessUnit@EDIT_BUSINESS_UNIT_SUCCEDED"
export const EDIT_BUSINESS_UNIT_FAILED = "businessUnit@EDIT_BUSINESS_UNIT_FAILED"
// disable business unit
export const DISABLE_BUSINESS_UNIT_INIT = "businessUnit@DISABLE_BUSINESS_UNIT_INIT"
export const DISABLE_BUSINESS_UNIT_SUCCEDED = "businessUnit@DISABLE_BUSINESS_UNIT_SUCCEDED"
export const DISABLE_BUSINESS_UNIT_FAILED = "businessUnit@DISABLE_BUSINESS_UNIT_FAILED"
// enable business unit
export const ENABLE_BUSINESS_UNIT_INIT = "businessUnit@ENABLE_BUSINESS_UNIT_INIT"
export const ENABLE_BUSINESS_UNIT_SUCCEDED = "businessUnit@ENABLE_BUSINESS_UNIT_SUCCEDED"
export const ENABLE_BUSINESS_UNIT_FAILED = "businessUnit@ENABLE_BUSINESS_UNIT_FAILED"
// disable all business units
export const DISABLE_ALL_BUSINESS_UNITS_INIT = "businessUnits@DISABLE_ALL_BUSINESS_UNITS_INIT"
export const DISABLE_ALL_BUSINESS_UNITS_SUCCEDED = "businessUnits@DISABLE_ALL_BUSINESS_UNITS_SUCCEDED"
export const DISABLE_ALL_BUSINESS_UNITS_FAILED = "businessUnits@DISABLE_ALL_BUSINESS_UNITS_FAILED"
// enable all business units
export const ENABLE_ALL_BUSINESS_UNITS_INIT = "businessUnits@ENABLE_ALL_BUSINESS_UNITS_INIT"
export const ENABLE_ALL_BUSINESS_UNITS_SUCCEDED = "businessUnits@ENABLE_ALL_BUSINESS_UNITS_SUCCEDED"
export const ENABLE_ALL_BUSINESS_UNITS_FAILED = "businessUnits@ENABLE_ALL_BUSINESS_UNITS_FAILED"
// delete business unit
export const DELETE_BUSINESS_UNIT_INIT = "businessUnit@DELETE_BUSINESS_UNIT_INIT"
export const DELETE_BUSINESS_UNIT_SUCCEDED = "businessUnit@DELETE_BUSINESS_UNIT_SUCCEDED"
export const DELETE_BUSINESS_UNIT_FAILED = "businessUnit@DELETE_BUSINESS_UNIT_FAILED"
// delete all business units
export const DELETE_ALL_BUSINESS_UNITS_INIT = "businessUnits@DELETE_ALL_BUSINESS_UNITS_INIT"
export const DELETE_ALL_BUSINESS_UNITS_SUCCEDED = "businessUnits@DELETE_ALL_BUSINESS_UNITS_SUCCEDED"
export const DELETE_ALL_BUSINESS_UNITS_FAILED = "businessUnits@DELETE_ALL_BUSINESS_UNITS_FAILED"
