export const BUSINESS_UNITS = "/api/business-units/"
export const BUSINESS_UNIT = "/api/business-units/:param"
export const BUSINESS_UNIT_DEACTIVATE = "/api/business-units/:param/deactivate"
export const BUSINESS_UNIT_ACTIVATE = "/api/business-units/:param/activate"
export const BUSINESS_UNITS_DEACTIVATE_ALL = "api/business-units/deactivate/all"
export const BUSINESS_UNITS_ACTIVATE_ALL = "/api/business-units/activate/all"
export const BUSINESS_UNIT_DELETE = "/api/business-units/:param/delete"
export const BUSINESS_UNITS_DELETE_ALL = "/api/business-units/delete/all"
