// candidate
export const CLEAR_CANDIDATE = "candidate@CLEAR_CANDIDATE"
export const FILTER_APPOINTMENT = "candidate@FILTER_APPOINTMENT"

export const FETCH_CANDIDATES_INIT = "candidate@FETCH_CANDIDATES_INIT"
export const FETCH_CANDIDATES_SUCCEDED = "candidate@FETCH_CANDIDATES_SUCCEDED"
export const FETCH_CANDIDATES_FAILED = "candidate@FETCH_CANDIDATES_FAILED"

export const SEARCH_CANDIDATES_INIT = "candidate@SEARCH_CANDIDATES_INIT"
export const SEARCH_CANDIDATES_SUCCEDED = "candidate@SEARCH_CANDIDATES_SUCCEDED"
export const SEARCH_CANDIDATES_FAILED = "candidate@SEARCH_CANDIDATES_FAILED"

export const CREATE_CANDIDATE_INIT = "candidate@CREATE_CANDIDATE_INIT"
export const CREATE_CANDIDATE_SUCCEDED = "candidate@CREATE_CANDIDATE_SUCCEDED"
export const CREATE_CANDIDATE_FAILED = "candidate@CREATE_CANDIDATE_FAILED"

export const FETCH_CANDIDATE_INIT = "candidate@FETCH_CANDIDATE_INIT"
export const FETCH_CANDIDATE_SUCCEDED = "candidate@FETCH_CANDIDATE_SUCCEDED"
export const FETCH_CANDIDATE_FAILED = "candidate@FETCH_CANDIDATE_FAILED"

export const EDIT_CANDIDATE_INIT = "candidate@EDIT_CANDIDATE_INIT"
export const EDIT_CANDIDATE_SUCCEDED = "candidate@EDIT_CANDIDATE_SUCCEDED"
export const EDIT_CANDIDATE_FAILED = "candidate@EDIT_CANDIDATE_FAILED"

export const DISABLE_CANDIDATE_INIT = "candidate@DISABLE_CANDIDATE_INIT"
export const DISABLE_CANDIDATE_SUCCEDED = "candidate@DISABLE_CANDIDATE_SUCCEDED"
export const DISABLE_CANDIDATE_FAILED = "candidate@DISABLE_CANDIDATE_FAILED"

export const ENABLE_CANDIDATE_INIT = "candidate@ENABLE_CANDIDATE_INIT"
export const ENABLE_CANDIDATE_SUCCEDED = "candidate@ENABLE_CANDIDATE_SUCCEDED"
export const ENABLE_CANDIDATE_FAILED = "candidate@ENABLE_CANDIDATE_FAILED"

export const DISABLE_CANDIDATES_INIT = "candidate@DISABLE_CANDIDATES_INIT"
export const DISABLE_CANDIDATES_SUCCEDED = "candidate@DISABLE_CANDIDATES_SUCCEDED"
export const DISABLE_CANDIDATES_FAILED = "candidate@DISABLE_CANDIDATES_FAILED"

export const ENABLE_CANDIDATES_INIT = "candidate@ENABLE_CANDIDATES_INIT"
export const ENABLE_CANDIDATES_SUCCEDED = "candidate@ENABLE_CANDIDATES_SUCCEDED"
export const ENABLE_CANDIDATES_FAILED = "candidate@ENABLE_CANDIDATES_FAILED"

export const FETCH_CANDIDATE_CONTENT_INIT = "candidate@FETCH_CANDIDATE_CONTENT_INIT"
export const FETCH_CANDIDATE_CONTENT_SUCCEDED = "candidate@FETCH_CANDIDATE_CONTENT_SUCCEDED"
export const FETCH_CANDIDATE_CONTENT_FAILED = "candidate@FETCH_CANDIDATE_CONTENT_FAILED"

export const EDIT_CANDIDATE_CONTENT_INIT = "candidate@EDIT_CANDIDATE_CONTENT_INIT"
export const EDIT_CANDIDATE_CONTENT_SUCCEDED = "candidate@EDIT_CANDIDATE_CONTENT_SUCCEDED"
export const EDIT_CANDIDATE_CONTENT_FAILED = "candidate@EDIT_CANDIDATE_CONTENT_FAILED"

export const FETCH_APPOINTMENT_INIT = "candidate@FETCH_APPOINTMENT_INIT"
export const FETCH_APPOINTMENT_SUCCEDED = "candidate@FETCH_APPOINTMENT_SUCCEDED"
export const FETCH_APPOINTMENT_FAILED = "candidate@FETCH_APPOINTMENT_FAILED"

export const FETCH_APPOINTMENTS_INIT = "candidate@FETCH_APPOINTMENTS_INIT"
export const FETCH_APPOINTMENTS_SUCCEDED = "candidate@FETCH_APPOINTMENTS_SUCCEDED"
export const FETCH_APPOINTMENTS_FAILED = "candidate@FETCH_APPOINTMENTS_FAILED"

export const FETCH_AVAILABILITIES_INIT = "candidate@FETCH_AVAILABILITIES_INIT"
export const FETCH_AVAILABILITIES_SUCCEDED = "candidate@FETCH_AVAILABILITIES_SUCCEDED"
export const FETCH_AVAILABILITIES_FAILED = "candidate@FETCH_AVAILABILITIES_FAILED"

export const CREATE_APPOINTMENT_INIT = "candidate@CREATE_APPOINTMENT_INIT"
export const CREATE_APPOINTMENT_SUCCEDED = "candidate@CREATE_APPOINTMENT_SUCCEDED"
export const CREATE_APPOINTMENT_FAILED = "candidate@CREATE_APPOINTMENT_FAILED"

export const EDIT_APPOINTMENT_INIT = "candidate@EDIT_APPOINTMENT_INIT"
export const EDIT_APPOINTMENT_SUCCEDED = "candidate@EDIT_APPOINTMENT_SUCCEDED"
export const EDIT_APPOINTMENT_FAILED = "candidate@EDIT_APPOINTMENT_FAILED"


export const FETCH_CANDIDATE_EXTRA_DATA_INIT = "candidate@FETCH_CANDIDATE_EXTRA_DATA_INIT"
export const FETCH_CANDIDATE_EXTRA_DATA_SUCCEDED = "candidate@FETCH_CANDIDATE_EXTRA_DATA_SUCCEDED"
export const FETCH_CANDIDATE_EXTRA_DATA_FAILED = "candidate@FETCH_CANDIDATE_EXTRA_DATA_FAILED"

export const EDIT_CANDIDATE_EXTRA_DATA_INIT = "candidate@EDIT_CANDIDATE_EXTRA_DATA_INIT"
export const EDIT_CANDIDATE_EXTRA_DATA_SUCCEDED = "candidate@EDIT_CANDIDATE_EXTRA_DATA_SUCCEDED"
export const EDIT_CANDIDATE_EXTRA_DATA_FAILED = "candidate@EDIT_CANDIDATE_EXTRA_DATA_FAILED"

export const CREATE_CANDIDATE_EXTRA_DATA_INIT = "candidate@CREATE_CANDIDATE_EXTRA_DATA_INIT"
export const CREATE_CANDIDATE_EXTRA_DATA_SUCCEDED = "candidate@CREATE_CANDIDATE_EXTRA_DATA_SUCCEDED"
export const CREATE_CANDIDATE_EXTRA_DATA_FAILED = "candidate@CREATE_CANDIDATE_EXTRA_DATA_FAILED"

export const CREATE_CANDIDATE_LANGUAGE_SUCCEDED="candidateLanguage@CREATE_CANDIDATE_LANGUAGE_SUCCEDED"
export const DELETE_CANDIDATE_LANGUAGE_SUCCEDED="candidateLanguage@DELETE_CANDIDATE_LANGUAGE_SUCCEDED"

export const EDIT_CANDIDATE_LANGUAGE_INIT="candidateLanguage@EDIT_CANDIDATE_LANGUAGE_INIT"
export const EDIT_CANDIDATE_LANGUAGE_SUCCEDED="candidateLanguage@EDIT_CANDIDATE_LANGUAGE_SUCCEDED"
export const EDIT_CANDIDATE_LANGUAGE_FAILED="candidateLanguage@EDIT_CANDIDATE_LANGUAGE_FAILED"

export const CANDIDATE_LANGUAGE_DISPLAY_INIT="candidateLanguageDisplay@CANDIDATE_LANGUAGE_DISPLAY_INIT"
export const CANDIDATE_LANGUAGE_DISPLAY_SUCCEDED="candidateLanguageDisplay@CANDIDATE_LANGUAGE_DISPLAY_SUCCEDED"
export const CANDIDATE_LANGUAGE_DISPLAY_FAILED="candidateLanguageDisplay@CANDIDATE_LANGUAGE_DISPLAY_FAILED"

export const CREATE_CANDIDATE_DOCUMENT_INIT = "candidateDocument@CREATE_CANDIDATE_DOCUMENT_INIT"
export const CREATE_CANDIDATE_DOCUMENT_SUCCEDED = "candidateDocument@CREATE_CANDIDATE_DOCUMENT_SUCCEDED"
export const CREATE_CANDIDATE_DOCUMENT_FAILED = "candidateDocument@CREATE_CANDIDATE_DOCUMENT_FAILED"

export const DELETE_CANDIDATE_DOCUMENT_INIT= "candidateDocument@DELETE_CANDIDATE_DOCUMENT_INIT"
export const DELETE_CANDIDATE_DOCUMENT_SUCCEDED= "candidateDocument@DELETE_CANDIDATE_DOCUMENT_SUCCEDED"
export const DELETE_CANDIDATE_DOCUMENT_FAILED= "candidateDocument@DELETE_CANDIDATE_DOCUMENT_FAILED"



export const EDIT_CANDIDATE_DOCUMENT_INIT="candidateDocument@EDIT_CANDIDATE_DOCUMENT_INIT"
export const EDIT_CANDIDATE_DOCUMENT_SUCCEDED="candidateDocument@EDIT_CANDIDATE_DOCUMENT_SUCCEDED"
export const EDIT_CANDIDATE_DOCUMENT_FAILED="candidateDocument@EDIT_CANDIDATE_DOCUMENT_FAILED"


export const CANDIDATE_DOCUMENT_DISPLAY_INIT="candidateDocumentDisplay@CANDIDATE_DOCUMENT_DISPLAY_INIT"
export const CANDIDATE_DOCUMENT_DISPLAY_SUCCEDED="candidateDocumentDisplay@CANDIDATE_DOCUMENT_DISPLAY_SUCCEDED"
export const CANDIDATE_DOCUMENT_DISPLAY_FAILED="candidateDocumentDisplay@CANDIDATE_DOCUMENT_DISPLAY_FAILED"

export const DOWNLOAD_DOCUMENT_INIT="candidateDocumentDisplay@CANDIDATE_DOWNLOAD_DOCUMENT_INIT"
export const DOWNLOAD_DOCUMENT_SUCCEDED="candidateDocumentDisplay@CANDIDATE_DOWNLOAD_DOCUMENT_SUCCEDED"
export const DOWNLOAD_DOCUMENT_FAILED="candidateDocumentDisplay@CANDIDATE_DOWNLOAD_DOCUMENT_FAILED"