export const CLEAR_ACTIVITY_TYPE = "activityType@CLEAR_ACTIVITY_TYPE"
// fetch legal agencies
export const FETCH_ACTIVITY_TYPES_INIT = "activityTypes@FETCH_ACTIVITY_TYPES_INIT"
export const FETCH_ACTIVITY_TYPES_SUCCEDED = "activityTypes@FETCH_ACTIVITY_TYPES_SUCCEDED"
export const FETCH_ACTIVITY_TYPES_FAILED = "activityTypes@FETCH_ACTIVITY_TYPES_FAILED"
// fetch legal agency
export const FETCH_ACTIVITY_TYPE_INIT = "activityType@FETCH_ACTIVITY_TYPE_INIT"
export const FETCH_ACTIVITY_TYPE_SUCCEDED = "activityType@FETCH_ACTIVITY_TYPE_SUCCEDED"
export const FETCH_ACTIVITY_TYPE_FAILED = "activityType@FETCH_ACTIVITY_TYPE_FAILED"
// create legal agency
export const CREATE_ACTIVITY_TYPE_INIT = "activityType@CREATE_ACTIVITY_TYPE_INIT"
export const CREATE_ACTIVITY_TYPE_SUCCEDED = "activityType@CREATE_ACTIVITY_TYPE_SUCCEDED"
export const CREATE_ACTIVITY_TYPE_FAILED = "activityType@CREATE_ACTIVITY_TYPE_FAILED"
// edit legal agency
export const EDIT_ACTIVITY_TYPE_INIT = "activityType@EDIT_ACTIVITY_TYPE_INIT"
export const EDIT_ACTIVITY_TYPE_SUCCEDED = "activityType@EDIT_ACTIVITY_TYPE_SUCCEDED"
export const EDIT_ACTIVITY_TYPE_FAILED = "activityType@EDIT_ACTIVITY_TYPE_FAILED"
// disable legal agency
export const DISABLE_ACTIVITY_TYPE_INIT = "activityType@DISABLE_ACTIVITY_TYPE_INIT"
export const DISABLE_ACTIVITY_TYPE_SUCCEDED = "activityType@DISABLE_ACTIVITY_TYPE_SUCCEDED"
export const DISABLE_ACTIVITY_TYPE_FAILED = "activityType@DISABLE_ACTIVITY_TYPE_FAILED"
// enable legal agency
export const ENABLE_ACTIVITY_TYPE_INIT = "activityType@ENABLE_ACTIVITY_TYPE_INIT"
export const ENABLE_ACTIVITY_TYPE_SUCCEDED = "activityType@ENABLE_ACTIVITY_TYPE_SUCCEDED"
export const ENABLE_ACTIVITY_TYPE_FAILED = "activityType@ENABLE_ACTIVITY_TYPE_FAILED"
// disable all legal agencies
export const DISABLE_ALL_ACTIVITY_TYPES_INIT = "activityTypes@DISABLE_ALL_ACTIVITY_TYPES_INIT"
export const DISABLE_ALL_ACTIVITY_TYPES_SUCCEDED = "activityTypes@DISABLE_ALL_ACTIVITY_TYPES_SUCCEDED"
export const DISABLE_ALL_ACTIVITY_TYPES_FAILED = "activityTypes@DISABLE_ALL_ACTIVITY_TYPES_FAILED"
// enable all legal agencies
export const ENABLE_ALL_ACTIVITY_TYPES_INIT = "activityTypes@ENABLE_ALL_ACTIVITY_TYPES_INIT"
export const ENABLE_ALL_ACTIVITY_TYPES_SUCCEDED = "activityTypes@ENABLE_ALL_ACTIVITY_TYPES_SUCCEDED"
export const ENABLE_ALL_ACTIVITY_TYPES_FAILED = "activityTypes@ENABLE_ALL_ACTIVITY_TYPES_FAILED"
// delete activity type
export const DELETE_ACTIVITY_TYPE_INIT = "activityType@DELETE_ACTIVITY_TYPE_INIT"
export const DELETE_ACTIVITY_TYPE_SUCCEDED = "activityType@DELETE_ACTIVITY_TYPE_SUCCEDED"
export const DELETE_ACTIVITY_TYPE_FAILED = "activityType@DELETE_ACTIVITY_TYPE_FAILED"
// delete all activity types
export const DELETE_ALL_ACTIVITY_TYPES_INIT = "activityTypes@DELETE_ALL_ACTIVITY_TYPES_INIT"
export const DELETE_ALL_ACTIVITY_TYPES_SUCCEDED = "activityTypes@DELETE_ALL_ACTIVITY_TYPES_SUCCEDED"
export const DELETE_ALL_ACTIVITY_TYPES_FAILED = "activityTypes@DELETE_ALL_ACTIVITY_TYPES_FAILED"
// fetch legal agency content data
export const FETCH_ACTIVITY_TYPE_CONTENT_INIT = "activityType@FETCH_ACTIVITY_TYPE_CONTENT_INIT"
export const FETCH_ACTIVITY_TYPE_CONTENT_SUCCEDED = "activityType@FETCH_ACTIVITY_TYPE_CONTENT_SUCCEDED"
export const FETCH_ACTIVITY_TYPE_CONTENT_FAILED = "activityType@FETCH_ACTIVITY_TYPE_CONTENT_FAILED"
// edit legal agency content data
export const EDIT_ACTIVITY_TYPE_CONTENT_INIT = "activityType@EDIT_ACTIVITY_TYPE_CONTENT_INIT"
export const EDIT_ACTIVITY_TYPE_CONTENT_SUCCEDED = "activityType@EDIT_ACTIVITY_TYPE_CONTENT_SUCCEDED"
export const EDIT_ACTIVITY_TYPE_CONTENT_FAILED = "activityType@EDIT_ACTIVITY_TYPE_CONTENT_FAILED"
// fetch legal agency extra data
export const FETCH_ACTIVITY_TYPE_EXTRA_DATA_INIT = "activityType@FETCH_ACTIVITY_TYPE_EXTRA_DATA_INIT"
export const FETCH_ACTIVITY_TYPE_EXTRA_DATA_SUCCEDED = "activityType@FETCH_ACTIVITY_TYPE_EXTRA_DATA_SUCCEDED"
export const FETCH_ACTIVITY_TYPE_EXTRA_DATA_FAILED = "activityType@FETCH_ACTIVITY_TYPE_EXTRA_DATA_FAILED"
// create legal agency extra data
export const CREATE_ACTIVITY_TYPE_EXTRA_DATA_INIT = "activityType@CREATE_ACTIVITY_TYPE_EXTRA_DATA_INIT"
export const CREATE_ACTIVITY_TYPE_EXTRA_DATA_SUCCEDED = "activityType@CREATE_ACTIVITY_TYPE_EXTRA_DATA_SUCCEDED"
export const CREATE_ACTIVITY_TYPE_EXTRA_DATA_FAILED = "activityType@CREATE_ACTIVITY_TYPE_EXTRA_DATA_FAILED"
// edit legal agency extra data
export const EDIT_ACTIVITY_TYPE_EXTRA_DATA_INIT = "activityType@EDIT_ACTIVITY_TYPE_EXTRA_DATA_INIT"
export const EDIT_ACTIVITY_TYPE_EXTRA_DATA_SUCCEDED = "activityType@EDIT_ACTIVITY_TYPE_EXTRA_DATA_SUCCEDED"
export const EDIT_ACTIVITY_TYPE_EXTRA_DATA_FAILED = "activityType@EDIT_ACTIVITY_TYPE_EXTRA_DATA_FAILED"
