export const ERROR_CODES = {
  404: "ERROR.CODE.NOT_FOUND",
  1100: "ERROR.CODE.BAD_CREDENTIALS",
  1101: "ERROR.CODE.INVALID_TOKEN",
  1102: "ERROR.CODE.BAD_TOKEN", 
  1103: "ERROR.CODE.RESET_PASSWORD_FAILED",
  1104: "ERROR.CODE.USER_ALREADY_EXIST",
  1200: "ERROR.CODE.WRONG_PASSWORD",
  1302: "ERROR.CODE.APPOINTMENT_TIME_IS_NOT_VALID"
}
