// school
export const CLEAR_SCHOOL = "school@CLEAR_SCHOOL"
export const FILTER_APPOINTMENT = "school@FILTER_APPOINTMENT"

export const FETCH_SCHOOLS_INIT = "school@FETCH_SCHOOLS_INIT"
export const FETCH_SCHOOLS_SUCCEDED = "school@FETCH_SCHOOLS_SUCCEDED"
export const FETCH_SCHOOLS_FAILED = "school@FETCH_SCHOOLS_FAILED"

export const CREATE_SCHOOL_INIT = "school@CREATE_SCHOOL_INIT"
export const CREATE_SCHOOL_SUCCEDED = "school@CREATE_SCHOOL_SUCCEDED"
export const CREATE_SCHOOL_FAILED = "school@CREATE_SCHOOL_FAILED"

export const FETCH_SCHOOL_INIT = "school@FETCH_SCHOOL_INIT"
export const FETCH_SCHOOL_SUCCEDED = "school@FETCH_SCHOOL_SUCCEDED"
export const FETCH_SCHOOL_FAILED = "school@FETCH_SCHOOL_FAILED"

export const EDIT_SCHOOL_INIT = "school@EDIT_SCHOOL_INIT"
export const EDIT_SCHOOL_SUCCEDED = "school@EDIT_SCHOOL_SUCCEDED"
export const EDIT_SCHOOL_FAILED = "school@EDIT_SCHOOL_FAILED"

export const DISABLE_SCHOOL_INIT = "school@DISABLE_SCHOOL_INIT"
export const DISABLE_SCHOOL_SUCCEDED = "school@DISABLE_SCHOOL_SUCCEDED"
export const DISABLE_SCHOOL_FAILED = "school@DISABLE_SCHOOL_FAILED"

export const ENABLE_SCHOOL_INIT = "school@ENABLE_SCHOOL_INIT"
export const ENABLE_SCHOOL_SUCCEDED = "school@ENABLE_SCHOOL_SUCCEDED"
export const ENABLE_SCHOOL_FAILED = "school@ENABLE_SCHOOL_FAILED"

export const DISABLE_SCHOOLS_INIT = "school@DISABLE_SCHOOLS_INIT"
export const DISABLE_SCHOOLS_SUCCEDED = "school@DISABLE_SCHOOLS_SUCCEDED"
export const DISABLE_SCHOOLS_FAILED = "school@DISABLE_SCHOOLS_FAILED"

export const ENABLE_SCHOOLS_INIT = "school@ENABLE_SCHOOLS_INIT"
export const ENABLE_SCHOOLS_SUCCEDED = "school@ENABLE_SCHOOLS_SUCCEDED"
export const ENABLE_SCHOOLS_FAILED = "school@ENABLE_SCHOOLS_FAILED"

export const FETCH_SCHOOL_CONTENT_INIT = "school@FETCH_SCHOOL_CONTENT_INIT"
export const FETCH_SCHOOL_CONTENT_SUCCEDED = "school@FETCH_SCHOOL_CONTENT_SUCCEDED"
export const FETCH_SCHOOL_CONTENT_FAILED = "school@FETCH_SCHOOL_CONTENT_FAILED"

export const EDIT_SCHOOL_CONTENT_INIT = "school@EDIT_SCHOOL_CONTENT_INIT"
export const EDIT_SCHOOL_CONTENT_SUCCEDED = "school@EDIT_SCHOOL_CONTENT_SUCCEDED"
export const EDIT_SCHOOL_CONTENT_FAILED = "school@EDIT_SCHOOL_CONTENT_FAILED"


export const FETCH_SCHOOL_EXTRA_DATA_INIT = "school@FETCH_SCHOOL_EXTRA_DATA_INIT"
export const FETCH_SCHOOL_EXTRA_DATA_SUCCEDED = "school@FETCH_SCHOOL_EXTRA_DATA_SUCCEDED"
export const FETCH_SCHOOL_EXTRA_DATA_FAILED = "school@FETCH_SCHOOL_EXTRA_DATA_FAILED"

export const EDIT_SCHOOL_EXTRA_DATA_INIT = "school@EDIT_SCHOOL_EXTRA_DATA_INIT"
export const EDIT_SCHOOL_EXTRA_DATA_SUCCEDED = "school@EDIT_SCHOOL_EXTRA_DATA_SUCCEDED"
export const EDIT_SCHOOL_EXTRA_DATA_FAILED = "school@EDIT_SCHOOL_EXTRA_DATA_FAILED"

export const CREATE_SCHOOL_EXTRA_DATA_INIT = "school@CREATE_SCHOOL_EXTRA_DATA_INIT"
export const CREATE_SCHOOL_EXTRA_DATA_SUCCEDED = "school@CREATE_SCHOOL_EXTRA_DATA_SUCCEDED"
export const CREATE_SCHOOL_EXTRA_DATA_FAILED = "school@CREATE_SCHOOL_EXTRA_DATA_FAILED"

export const CREATE_SCHOOL_DOCUMENT_SUCCEDED = "schoolDocument@CREATE_SCHOOL_DOCUMENT_SUCCEDED"
export const EDIT_SCHOOL_DOCUMENT_SUCCEDED = "schoolDocument@EDIT_SCHOOL_DOCUMENT_SUCCEDED"
export const DELETE_SCHOOL_DOCUMENT_SUCCEDED = "schoolDocument@DELETE_SCHOOL_DOCUMENT_SUCCEDED"
