version: '3'

services:
  e_hiring_front:
    image: registry.gitlab.com/aakrout/e_hiring_front:v1
    env_file:
      - ./.env
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 500mb
        reservations:
          memory: 256mb
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.scp-e_hiring-staging-front.rule=Host(`ehiring.infinitymgt.fr`)"
        - "traefik.http.routers.scp-e_hiring-staging-front.entrypoints=websecure"
        - "traefik.http.routers.scp-e_hiring-staging-front.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.scp-e_hiring-staging-front-srv.loadbalancer.server.port=8080"

networks:
  default:
    external:
      name: traefik-net
