export const CLEAR_LEGAL_AGENCY = "legalAgency@CLEAR_LEGAL_AGENCY"
// fetch legal agencies
export const FETCH_LEGAL_AGENCIES_INIT = "legalAgencies@FETCH_LEGAL_AGENCIES_INIT"
export const FETCH_LEGAL_AGENCIES_SUCCEDED = "legalAgencies@FETCH_LEGAL_AGENCIES_SUCCEDED"
export const FETCH_LEGAL_AGENCIES_FAILED = "legalAgencies@FETCH_LEGAL_AGENCIES_FAILED"
// fetch legal agency
export const FETCH_LEGAL_AGENCY_INIT = "legalAgency@FETCH_LEGAL_AGENCY_INIT"
export const FETCH_LEGAL_AGENCY_SUCCEDED = "legalAgency@FETCH_LEGAL_AGENCY_SUCCEDED"
export const FETCH_LEGAL_AGENCY_FAILED = "legalAgency@FETCH_LEGAL_AGENCY_FAILED"
// create legal agency
export const CREATE_LEGAL_AGENCY_INIT = "legalAgency@CREATE_LEGAL_AGENCY_INIT"
export const CREATE_LEGAL_AGENCY_SUCCEDED = "legalAgency@CREATE_LEGAL_AGENCY_SUCCEDED"
export const CREATE_LEGAL_AGENCY_FAILED = "legalAgency@CREATE_LEGAL_AGENCY_FAILED"
// edit legal agency
export const EDIT_LEGAL_AGENCY_INIT = "legalAgency@EDIT_LEGAL_AGENCY_INIT"
export const EDIT_LEGAL_AGENCY_SUCCEDED = "legalAgency@EDIT_LEGAL_AGENCY_SUCCEDED"
export const EDIT_LEGAL_AGENCY_FAILED = "legalAgency@EDIT_LEGAL_AGENCY_FAILED"
// disable legal agency
export const DISABLE_LEGAL_AGENCY_INIT = "legalAgency@DISABLE_LEGAL_AGENCY_INIT"
export const DISABLE_LEGAL_AGENCY_SUCCEDED = "legalAgency@DISABLE_LEGAL_AGENCY_SUCCEDED"
export const DISABLE_LEGAL_AGENCY_FAILED = "legalAgency@DISABLE_LEGAL_AGENCY_FAILED"
// enable legal agency
export const ENABLE_LEGAL_AGENCY_INIT = "legalAgency@ENABLE_LEGAL_AGENCY_INIT"
export const ENABLE_LEGAL_AGENCY_SUCCEDED = "legalAgency@ENABLE_LEGAL_AGENCY_SUCCEDED"
export const ENABLE_LEGAL_AGENCY_FAILED = "legalAgency@ENABLE_LEGAL_AGENCY_FAILED"
// disable all legal agencies
export const DISABLE_ALL_LEGAL_AGENCIES_INIT = "legalAgencies@DISABLE_ALL_LEGAL_AGENCIES_INIT"
export const DISABLE_ALL_LEGAL_AGENCIES_SUCCEDED = "legalAgencies@DISABLE_ALL_LEGAL_AGENCIES_SUCCEDED"
export const DISABLE_ALL_LEGAL_AGENCIES_FAILED = "legalAgencies@DISABLE_ALL_LEGAL_AGENCIES_FAILED"
// enable all legal agencies
export const ENABLE_ALL_LEGAL_AGENCIES_INIT = "legalAgencies@ENABLE_ALL_LEGAL_AGENCIES_INIT"
export const ENABLE_ALL_LEGAL_AGENCIES_SUCCEDED = "legalAgencies@ENABLE_ALL_LEGAL_AGENCIES_SUCCEDED"
export const ENABLE_ALL_LEGAL_AGENCIES_FAILED = "legalAgencies@ENABLE_ALL_LEGAL_AGENCIES_FAILED"
// fetch legal agency content data
export const FETCH_LEGAL_AGENCY_CONTENT_INIT = "legalAgency@FETCH_LEGAL_AGENCY_CONTENT_INIT"
export const FETCH_LEGAL_AGENCY_CONTENT_SUCCEDED = "legalAgency@FETCH_LEGAL_AGENCY_CONTENT_SUCCEDED"
export const FETCH_LEGAL_AGENCY_CONTENT_FAILED = "legalAgency@FETCH_LEGAL_AGENCY_CONTENT_FAILED"
// edit legal agency content data
export const EDIT_LEGAL_AGENCY_CONTENT_INIT = "legalAgency@EDIT_LEGAL_AGENCY_CONTENT_INIT"
export const EDIT_LEGAL_AGENCY_CONTENT_SUCCEDED = "legalAgency@EDIT_LEGAL_AGENCY_CONTENT_SUCCEDED"
export const EDIT_LEGAL_AGENCY_CONTENT_FAILED = "legalAgency@EDIT_LEGAL_AGENCY_CONTENT_FAILED"
// fetch legal agency extra data
export const FETCH_LEGAL_AGENCY_EXTRA_DATA_INIT = "legalAgency@FETCH_LEGAL_AGENCY_EXTRA_DATA_INIT"
export const FETCH_LEGAL_AGENCY_EXTRA_DATA_SUCCEDED = "legalAgency@FETCH_LEGAL_AGENCY_EXTRA_DATA_SUCCEDED"
export const FETCH_LEGAL_AGENCY_EXTRA_DATA_FAILED = "legalAgency@FETCH_LEGAL_AGENCY_EXTRA_DATA_FAILED"
// create legal agency extra data
export const CREATE_LEGAL_AGENCY_EXTRA_DATA_INIT = "legalAgency@CREATE_LEGAL_AGENCY_EXTRA_DATA_INIT"
export const CREATE_LEGAL_AGENCY_EXTRA_DATA_SUCCEDED = "legalAgency@CREATE_LEGAL_AGENCY_EXTRA_DATA_SUCCEDED"
export const CREATE_LEGAL_AGENCY_EXTRA_DATA_FAILED = "legalAgency@CREATE_LEGAL_AGENCY_EXTRA_DATA_FAILED"
// edit legal agency extra data
export const EDIT_LEGAL_AGENCY_EXTRA_DATA_INIT = "legalAgency@EDIT_LEGAL_AGENCY_EXTRA_DATA_INIT"
export const EDIT_LEGAL_AGENCY_EXTRA_DATA_SUCCEDED = "legalAgency@EDIT_LEGAL_AGENCY_EXTRA_DATA_SUCCEDED"
export const EDIT_LEGAL_AGENCY_EXTRA_DATA_FAILED = "legalAgency@EDIT_LEGAL_AGENCY_EXTRA_DATA_FAILED"
