// job
export const CLEAR_JOB = "job@CLEAR_JOB"
export const FILTER_APPOINTMENT = "job@FILTER_APPOINTMENT"

export const FETCH_JOBS_INIT = "job@FETCH_JOBS_INIT"
export const FETCH_JOBS_SUCCEDED = "job@FETCH_JOBS_SUCCEDED"
export const FETCH_JOBS_FAILED = "job@FETCH_JOBS_FAILED"

export const CREATE_JOB_INIT = "job@CREATE_JOB_INIT"
export const CREATE_JOB_SUCCEDED = "job@CREATE_JOB_SUCCEDED"
export const CREATE_JOB_FAILED = "job@CREATE_JOB_FAILED"

export const FETCH_JOB_INIT = "job@FETCH_JOB_INIT"
export const FETCH_JOB_SUCCEDED = "job@FETCH_JOB_SUCCEDED"
export const FETCH_JOB_FAILED = "job@FETCH_JOB_FAILED"

export const EDIT_JOB_INIT = "job@EDIT_JOB_INIT"
export const EDIT_JOB_SUCCEDED = "job@EDIT_JOB_SUCCEDED"
export const EDIT_JOB_FAILED = "job@EDIT_JOB_FAILED"

export const DISABLE_JOB_INIT = "job@DISABLE_JOB_INIT"
export const DISABLE_JOB_SUCCEDED = "job@DISABLE_JOB_SUCCEDED"
export const DISABLE_JOB_FAILED = "job@DISABLE_JOB_FAILED"

export const VALIDATE_JOB_INIT = "job@VALIDATE_JOB_INIT"
export const VALIDATE_JOB_SUCCEDED = "job@VALIDATE_JOB_SUCCEDED"
export const VALIDATE_JOB_FAILED = "job@VALIDATE_JOB_FAILED"

export const REJECT_JOB_INIT = "job@REJECT_JOB_INIT"
export const REJECT_JOB_SUCCEDED = "job@REJECT_JOB_SUCCEDED"
export const REJECT_JOB_FAILED = "job@REJECT_JOB_FAILED"

export const ENABLE_JOB_INIT = "job@ENABLE_JOB_INIT"
export const ENABLE_JOB_SUCCEDED = "job@ENABLE_JOB_SUCCEDED"
export const ENABLE_JOB_FAILED = "job@ENABLE_JOB_FAILED"

export const DISABLE_JOBS_INIT = "job@DISABLE_JOBS_INIT"
export const DISABLE_JOBS_SUCCEDED = "job@DISABLE_JOBS_SUCCEDED"
export const DISABLE_JOBS_FAILED = "job@DISABLE_JOBS_FAILED"

export const ENABLE_JOBS_INIT = "job@ENABLE_JOBS_INIT"
export const ENABLE_JOBS_SUCCEDED = "job@ENABLE_JOBS_SUCCEDED"
export const ENABLE_JOBS_FAILED = "job@ENABLE_JOBS_FAILED"


export const FETCH_JOB_EXTRA_DATA_INIT = "job@FETCH_JOB_EXTRA_DATA_INIT"
export const FETCH_JOB_EXTRA_DATA_SUCCEDED = "job@FETCH_JOB_EXTRA_DATA_SUCCEDED"
export const FETCH_JOB_EXTRA_DATA_FAILED = "job@FETCH_JOB_EXTRA_DATA_FAILED"

export const EDIT_JOB_EXTRA_DATA_INIT = "job@EDIT_JOB_EXTRA_DATA_INIT"
export const EDIT_JOB_EXTRA_DATA_SUCCEDED = "job@EDIT_JOB_EXTRA_DATA_SUCCEDED"
export const EDIT_JOB_EXTRA_DATA_FAILED = "job@EDIT_JOB_EXTRA_DATA_FAILED"

export const CREATE_JOB_EXTRA_DATA_INIT = "job@CREATE_JOB_EXTRA_DATA_INIT"
export const CREATE_JOB_EXTRA_DATA_SUCCEDED = "job@CREATE_JOB_EXTRA_DATA_SUCCEDED"
export const CREATE_JOB_EXTRA_DATA_FAILED = "job@CREATE_JOB_EXTRA_DATA_FAILED"

export const CREATE_JOB_DOCUMENT_SUCCEDED = "jobDocument@CREATE_JOB_DOCUMENT_SUCCEDED"
export const EDIT_JOB_DOCUMENT_SUCCEDED = "jobDocument@EDIT_JOB_DOCUMENT_SUCCEDED"
export const DELETE_JOB_DOCUMENT_SUCCEDED = "jobDocument@DELETE_JOB_DOCUMENT_SUCCEDED"
