// offer
export const CLEAR_OFFER = "offer@CLEAR_OFFER"
export const FILTER_APPOINTMENT = "offer@FILTER_APPOINTMENT"

export const FETCH_OFFERS_INIT = "offer@FETCH_OFFERS_INIT"
export const FETCH_OFFERS_SUCCEDED = "offer@FETCH_OFFERS_SUCCEDED"
export const FETCH_OFFERS_FAILED = "offer@FETCH_OFFERS_FAILED"

export const CREATE_OFFER_INIT = "offer@CREATE_OFFER_INIT"
export const CREATE_OFFER_SUCCEDED = "offer@CREATE_OFFER_SUCCEDED"
export const CREATE_OFFER_FAILED = "offer@CREATE_OFFER_FAILED"

export const FETCH_OFFER_INIT = "offer@FETCH_OFFER_INIT"
export const FETCH_OFFER_SUCCEDED = "offer@FETCH_OFFER_SUCCEDED"
export const FETCH_OFFER_FAILED = "offer@FETCH_OFFER_FAILED"

export const EDIT_OFFER_INIT = "offer@EDIT_OFFER_INIT"
export const EDIT_OFFER_SUCCEDED = "offer@EDIT_OFFER_SUCCEDED"
export const EDIT_OFFER_FAILED = "offer@EDIT_OFFER_FAILED"

export const DISABLE_OFFER_INIT = "offer@DISABLE_OFFER_INIT"
export const DISABLE_OFFER_SUCCEDED = "offer@DISABLE_OFFER_SUCCEDED"
export const DISABLE_OFFER_FAILED = "offer@DISABLE_OFFER_FAILED"

export const ENABLE_OFFER_INIT = "offer@ENABLE_OFFER_INIT"
export const ENABLE_OFFER_SUCCEDED = "offer@ENABLE_OFFER_SUCCEDED"
export const ENABLE_OFFER_FAILED = "offer@ENABLE_OFFER_FAILED"

export const DISABLE_OFFERS_INIT = "offer@DISABLE_OFFERS_INIT"
export const DISABLE_OFFERS_SUCCEDED = "offer@DISABLE_OFFERS_SUCCEDED"
export const DISABLE_OFFERS_FAILED = "offer@DISABLE_OFFERS_FAILED"

export const CLOSE_OFFER_INIT = "offer@CLOSE_OFFER_INIT"
export const CLOSE_OFFER_SUCCEDED = "offer@CLOSE_OFFER_SUCCEDED"
export const CLOSE_OFFER_FAILED = "offer@CLOSE_OFFER_FAILED"

export const VALIDATE_OFFER_INIT = "offer@VALIDATE_OFFER_INIT"
export const VALIDATE_OFFER_SUCCEDED = "offer@VALIDATE_OFFER_SUCCEDED"
export const VALIDATE_OFFER_FAILED = "offer@VALIDATE_OFFER_FAILED"

export const ENABLE_OFFERS_INIT = "offer@ENABLE_OFFERS_INIT"
export const ENABLE_OFFERS_SUCCEDED = "offer@ENABLE_OFFERS_SUCCEDED"
export const ENABLE_OFFERS_FAILED = "offer@ENABLE_OFFERS_FAILED"

export const FETCH_OFFER_CONTENT_INIT = "offer@FETCH_OFFER_CONTENT_INIT"
export const FETCH_OFFER_CONTENT_SUCCEDED = "offer@FETCH_OFFER_CONTENT_SUCCEDED"
export const FETCH_OFFER_CONTENT_FAILED = "offer@FETCH_OFFER_CONTENT_FAILED"

export const EDIT_OFFER_CONTENT_INIT = "offer@EDIT_OFFER_CONTENT_INIT"
export const EDIT_OFFER_CONTENT_SUCCEDED = "offer@EDIT_OFFER_CONTENT_SUCCEDED"
export const EDIT_OFFER_CONTENT_FAILED = "offer@EDIT_OFFER_CONTENT_FAILED"


export const FETCH_OFFER_EXTRA_DATA_INIT = "offer@FETCH_OFFER_EXTRA_DATA_INIT"
export const FETCH_OFFER_EXTRA_DATA_SUCCEDED = "offer@FETCH_OFFER_EXTRA_DATA_SUCCEDED"
export const FETCH_OFFER_EXTRA_DATA_FAILED = "offer@FETCH_OFFER_EXTRA_DATA_FAILED"

export const EDIT_OFFER_EXTRA_DATA_INIT = "offer@EDIT_OFFER_EXTRA_DATA_INIT"
export const EDIT_OFFER_EXTRA_DATA_SUCCEDED = "offer@EDIT_OFFER_EXTRA_DATA_SUCCEDED"
export const EDIT_OFFER_EXTRA_DATA_FAILED = "offer@EDIT_OFFER_EXTRA_DATA_FAILED"

export const CREATE_OFFER_EXTRA_DATA_INIT = "offer@CREATE_OFFER_EXTRA_DATA_INIT"
export const CREATE_OFFER_EXTRA_DATA_SUCCEDED = "offer@CREATE_OFFER_EXTRA_DATA_SUCCEDED"
export const CREATE_OFFER_EXTRA_DATA_FAILED = "offer@CREATE_OFFER_EXTRA_DATA_FAILED"

export const CREATE_OFFER_DOCUMENT_SUCCEDED = "offerDocument@CREATE_OFFER_DOCUMENT_SUCCEDED"
export const EDIT_OFFER_DOCUMENT_SUCCEDED = "offerDocument@EDIT_OFFER_DOCUMENT_SUCCEDED"
export const DELETE_OFFER_DOCUMENT_SUCCEDED = "offerDocument@DELETE_OFFER_DOCUMENT_SUCCEDED"

// kanban
export const CLEAR_KANBAN = "offer@CLEAR_KANBAN"

export const CREATE_KANBAN_INIT = "offer@CREATE_KANBAN_INIT"
export const CREATE_KANBAN_SUCCEDED = "offer@CREATE_KANBAN_SUCCEDED"
export const CREATE_KANBAN_FAILED = "offer@CREATE_KANBAN_FAILED"

export const FETCH_KANBAN_CANDIDATES_INIT = "offer@FETCH_KANBAN_CANDIDATES_INIT"
export const FETCH_KANBAN_CANDIDATES_SUCCEDED = "offer@FETCH_KANBAN_CANDIDATES_SUCCEDED"
export const FETCH_KANBAN_CANDIDATES_FAILED = "offer@FETCH_KANBAN_CANDIDATES_FAILED"

export const DELETE_KANBAN_INIT = "offer@DELETE_KANBAN_INIT"
export const DELETE_KANBAN_SUCCEDED = "offer@DELETE_KANBAN_SUCCEDED"
export const DELETE_KANBAN_FAILED = "offer@DELETE_KANBAN_FAILED"

export const SHARE_CV_INIT = "offer@SHARE_CV_INIT"
export const SHARE_CV_SUCCEDED = "offer@SHARE_CV_SUCCEDED"
export const SHARE_CV_FAILED = "offer@SHARE_CV_FAILED"

// Appointments
export const CREATE_APPOINTMENT_INIT = "offer@CREATE_APPOINTMENT_INIT"
export const CREATE_APPOINTMENT_SUCCEDED = "offer@CREATE_APPOINTMENT_SUCCEDED"
export const CREATE_APPOINTMENT_FAILED = "offer@CREATE_APPOINTMENT_FAILED"

export const FETCH_APPOINTMENT_INIT = "offer@FETCH_APPOINTMENT_INIT"
export const FETCH_APPOINTMENT_SUCCEDED = "offer@FETCH_APPOINTMENT_SUCCEDED"
export const FETCH_APPOINTMENT_FAILED = "offer@FETCH_APPOINTMENT_FAILED"

export const EDIT_APPOINTMENT_INIT="offer@EDIT_APPOINTMENT_INIT"
export const EDIT_APPOINTMENT_SUCCEDED="offer@EDIT_APPOINTMENT_SUCCEDED"
export const EDIT_APPOINTMENT_FAILED="offer@EDIT_APPOINTMENT_FAILED"

export const DELETE_APPOINTMENT_INIT="offer@DELETE_APPOINTMENT_INIT"
export const DELETE_APPOINTMENT_SUCCEDED="offer@DELETE_APPOINTMENT_SUCCEDED"
export const DELETE_APPOINTMENT_FAILED="offer@DELETE_APPOINTMENT_FAILED"


export const FETCH_APPOINTMENT_EXTRA_DATA_INIT = "offer@FETCH_APPOINTMENT_EXTRA_DATA_INIT"
export const FETCH_APPOINTMENT_EXTRA_DATA_SUCCEDED = "offer@FETCH_APPOINTMENT_EXTRA_DATA_SUCCEDED"
export const FETCH_APPOINTMENT_EXTRA_DATA_FAILED = "offer@FETCH_APPOINTMENT_EXTRA_DATA_FAILED"