// resourceState
export const FETCH_RESOURCE_STATES_INIT = "resourceStates@FETCH_RESOURCE_STATES_INIT"
export const FETCH_RESOURCE_STATES_SUCCEDED = "resourceStates@FETCH_RESOURCE_STATES_SUCCEDED"
export const FETCH_RESOURCE_STATES_FAILED = "resourceStates@FETCH_RESOURCE_STATES_FAILED"

export const CLEAR_RESOURCE_STATE = "resourceState@CLEAR_RESOURCE_STATE"

export const CREATE_RESOURCE_STATE_INIT = "resourceState@CREATE_RESOURCE_STATE_INIT"
export const CREATE_RESOURCE_STATE_SUCCEDED = "resourceState@CREATE_RESOURCE_STATE_SUCCEDED"
export const CREATE_RESOURCE_STATE_FAILED = "resourceState@CREATE_RESOURCE_STATE_FAILED"

export const FETCH_RESOURCE_STATE_INIT = "resourceState@FETCH_RESOURCE_STATE_INIT"
export const FETCH_RESOURCE_STATE_SUCCEDED = "resourceState@FETCH_RESOURCE_STATE_SUCCEDED"
export const FETCH_RESOURCE_STATE_FAILED = "resourceState@FETCH_RESOURCE_STATE_FAILED"

export const EDIT_RESOURCE_STATE_INIT = "resourceState@EDIT_RESOURCE_STATE_INIT"
export const EDIT_RESOURCE_STATE_SUCCEDED = "resourceState@EDIT_RESOURCE_STATE_SUCCEDED"
export const EDIT_RESOURCE_STATE_FAILED = "resourceState@EDIT_RESOURCE_STATE_FAILED"

export const DELETE_RESOURCE_STATE_INIT = "resourceState@DELETE_RESOURCE_STATE_INIT"
export const DELETE_RESOURCE_STATE_SUCCEDED = "resourceState@DELETE_RESOURCE_STATE_SUCCEDED"
export const DELETE_RESOURCE_STATE_FAILED = "resourceState@DELETE_RESOURCE_STATE_FAILED"

export const DEACTIVATE_RESOURCE_STATE_INIT = "resourceState@DEACTIVATE_RESOURCE_STATE_INIT"
export const DEACTIVATE_RESOURCE_STATE_SUCCEDED = "resourceState@DEACTIVATE_RESOURCE_STATE_SUCCEDED"
export const DEACTIVATE_RESOURCE_STATE_FAILED = "resourceState@DEACTIVATE_RESOURCE_STATE_FAILED"

export const ACTIVATE_RESOURCE_STATE_INIT = "resourceState@ACTIVATE_RESOURCE_STATE_INIT"
export const ACTIVATE_RESOURCE_STATE_SUCCEDED = "resourceState@ACTIVATE_RESOURCE_STATE_SUCCEDED"
export const ACTIVATE_RESOURCE_STATE_FAILED = "resourceState@ACTIVATE_RESOURCE_STATE_FAILED"

export const DELETE_ALL_RESOURCE_STATES_INIT = "resourceStates@DELETE_ALL_RESOURCE_STATES_INIT"
export const DELETE_ALL_RESOURCE_STATES_SUCCEDED = "resourceStates@DELETE_ALL_RESOURCE_STATES_SUCCEDED"
export const DELETE_ALL_RESOURCE_STATES_FAILED = "resourceStates@DELETE_ALL_RESOURCE_STATES_FAILED"

export const DEACTIVATE_ALL_RESOURCE_STATES_INIT = "resourceStates@DEACTIVATE_ALL_RESOURCE_STATES_INIT"
export const DEACTIVATE_ALL_RESOURCE_STATES_SUCCEDED = "resourceStates@DEACTIVATE_ALL_RESOURCE_STATES_SUCCEDED"
export const DEACTIVATE_ALL_RESOURCE_STATES_FAILED = "resourceStates@DEACTIVATE_ALL_RESOURCE_STATES_FAILED"

export const ACTIVATE_ALL_RESOURCE_STATES_INIT = "resourceStates@ACTIVATE_ALL_RESOURCE_STATES_INIT"
export const ACTIVATE_ALL_RESOURCE_STATES_SUCCEDED = "resourceStates@ACTIVATE_ALL_RESOURCE_STATES_SUCCEDED"
export const ACTIVATE_ALL_RESOURCE_STATES_FAILED = "resourceStates@ACTIVATE_ALL_RESOURCE_STATES_FAILED"



